//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XmlRsa.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XmlRsa.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;RSAKeyValue&gt;&lt;Modulus&gt;yXA14h2M/bLlMsERDyy9ErTh6VyFklaN+8GfMxQkVNcx9IS0AESWgVX49w802EcrYZib1oGJuPW1HTX1A1eyb75JXkolq2mSHr+GCjMqV7xlTljOf7u42av0kZKNOvWUQEDo/aOtYpOZH7CSmA3f4dhBGdLoh7TqhB/fGdMwnEk=&lt;/Modulus&gt;&lt;Exponent&gt;AQAB&lt;/Exponent&gt;&lt;P&gt;904FD9XlvXN2bF4lOrEID/Coo64M5yJBDJd2XAHEzG/THadrSHag0Wt5VfCEOqJG1T0gVm+iEZI8uxN/Z8FM8w==&lt;/P&gt;&lt;Q&gt;0IVZRNVK+6BHQJoaTL19Nv8k1I/wEj9F57xRBxy/YcwD9LrGiFGEpqkvoEq80SNogjcrxoAnY6ktw4aIdXUQ0w==&lt;/Q&gt;&lt;DP&gt;FaIwlSsL9t+z21T9Ar5byzEtP2xJWqrHb/eL9g59jbi2iiCMJQGjnc4+BgONPafWdG7tdkI7tjfJsj/JZGUnew==&lt; [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string priv {
            get {
                return ResourceManager.GetString("priv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;RSAKeyValue&gt;&lt;Modulus&gt;yXA14h2M/bLlMsERDyy9ErTh6VyFklaN+8GfMxQkVNcx9IS0AESWgVX49w802EcrYZib1oGJuPW1HTX1A1eyb75JXkolq2mSHr+GCjMqV7xlTljOf7u42av0kZKNOvWUQEDo/aOtYpOZH7CSmA3f4dhBGdLoh7TqhB/fGdMwnEk=&lt;/Modulus&gt;&lt;Exponent&gt;AQAB&lt;/Exponent&gt;&lt;/RSAKeyValue&gt;.
        /// </summary>
        internal static string pub {
            get {
                return ResourceManager.GetString("pub", resourceCulture);
            }
        }
    }
}
